### PR TITLE
Clean up network profiles

### PR DESCRIPTION
**Pull request by itiligent**
(Resubmitted do to an issue with the copyright not adding somehow) 

As requested by @oskardotglobal. This PR will help keep Windows networking tidy. The install.bat changes will:

Create a new powershell script and save this to c:\windows. The Powershell script will clear unused network profile names that were automatically created at previous system reboots.
Install.bat also creates a new scheduled task that will run the cleanup powershell script at boot
A registry change is further added to RDPapps.reg to disable the "Do you want your PC to be discoverable" nag screen after each reboot
I've also added simple comments to each of the reg file entries for clarity.

### CODE REVIEW

**Comment by oskardotglobal** [comment]
great, now CI passes but still doesn't do anything

**Review by KernelGhost — APPROVED** [review]
Seems fine based on a cursory look. Thanks for the changes!

**Comment by itiligent** [comment]
You're welcome. Its just a small quality of life change that also makes the WinApps OOB experience feel a bit nicer.  Its been tested in multiple settings and runs fine.

**Comment by itiligent** [comment]
sorry, meant to comment not close! I need my glasses!

**Pull request merged**
