### PR TITLE
Display warnings when changing RDP_SCALE automatically to prevent user confusion.

### PR DESCRIPTION
**Pull request by KernelGhost**
As requested by LDprg in PR #144.

### CODE REVIEW

**Review by LDprg — APPROVED** [review]
Seems good to me. Thx.

**Review by LDprg — APPROVED** [review]
@KernelGhost no problem, I am happy to see this fixes.

**Comment by LDprg** [comment]
@oskardotglobal There is a difference between the two. 

Afaik Freerdp mounts the directory when connecting via the rdp protocol. Here qemu mounts the directory directly into the vm without the need of an connected client.

**Comment by KernelGhost** [comment]
@oskardotglobal Yes, FreeRDP mounts the Linux home directory when `+home-drive` is used as an argument. As @LDprg mentioned, this additional mount allows access to the Linux home directory when the user is viewing the Windows VM via http://127.0.0.1:8006. I thought adding this additional mount might be useful during the initial setup of the VM, as the user may have certain files or programs stored on Linux that they wish to access from Windows prior to installing WinApps. This mount can be turned off by the user by commenting out the relevant line within `compose.yaml`.

**Comment by KernelGhost** [comment]
My most recent set of commits add official support for `podman` as a daemonless alternative to using `docker` for the virtual machine backend. The relevant documentation has also been updated to reflect this.

**Comment by KernelGhost** [comment]
The latest commit also fixes #91. Credit goes to [f8ith](https://github.com/f8ith) for identifying the cause of the issue.

**Comment by KernelGhost** [comment]
I do not foresee making any further commits to this pull request. Please feel free to merge it when appropriate. Thanks!

**Review by oskardotglobal — COMMENTED** [review]
LGTM.

**Pull request merged**
