### PR TITLE
[Code Refactor] Improved Installation Script

### PR DESCRIPTION
**Pull request by KernelGhost**
This constitutes a major rewrite of the WinApps installation script.

Key Changes:
- Enhanced error handling and messaging.
- Increased robustness through the addition of various new checks during the installation process.
- Removal of superfluous functions and calls to non-existent functions.
- Updated `FreeRDP` command to implement a 'TOFU' policy for certificates, thereby removing the need to run `winapps check` prior to installation.
- Correction of various typos.

Verification:
- [x] No ShellCheck warnings reported.
- [X] Revised script performs as expected during extensive local testing.

Apologies for the single commit! I initially did not plan on refactoring the entire script.

Please review the changes and let me know if there are any questions or additional improvements needed.

Thank you!

### CODE REVIEW

**Comment by KernelGhost** [comment]
It appears I have accidentally included previously submitted changes to `bin/winapps` in this pull request, my apologies. In addition, it appears that the pre-commit.ci bot has automatically introduced a number of erroneous whitespace changes to `installer.sh`, which will need to be reverted.

**Review by KernelGhost — COMMENTED** [review]
These whitespace changes are not benign, and appear to have been erroneously committed by the pre-commit bot.

**Comment by oskardotglobal** [comment]
First of all, thanks for the amazing work.
However, if we're rewriting this anyways, I would like to propose 2 major changes:
1. Fully drop support for virsh and exclusively use RDP_IP for the connection
2. Update / replace inquirer.sh as there seems to be some issues with it (e.g. #127)

CC @LDprg

**Comment by oskardotglobal** [comment]
I've also gone ahead and merged #123 so those bin/winapps changes don't apply anymore

**Comment by LDprg** [comment]
First of all great thanks to @KernelGhost!

@oskardotglobal I totally agree that those things would be great to be included here (if @KernelGhost is willing to do so).

Another thing would be the readdition for freerdp2 support (by switching the arguments depending of the version). But I guess this should be a own pr after this one.

**Comment by KernelGhost** [comment]
I've made additional optimisations to the installation script and have also updated `inquirer.sh` as per your request.

Currently, I've been using WinApps with `virt-manager`, so I'm not fully acquainted with the docker-based approach just yet. I'll make an effort to eliminate mentions of `virsh` from `installer.sh`, but if someone else is more confident in handling this task, they are welcome to take the lead before I do.

I agree support for `FreeRDP` version 2 should be reintroduced in a separate pull request.

Annoyingly, the pre-commit bot has yet again introduced troublesome white space changes with commit `deec264`, and these will need to be reverted.

In the meantime, should we proceed with merging this pull request? The issues regarding the deprecation of libvirt and reintroducing support for freerdp2 can be addressed within this PR, but doing so will delay the release of various improvements and bug fixes also included.

I also encourage others to test my changes thoroughly. I have done my best to ensure the scripts are of quality, but a second (or third) pair of eyes wouldn't hurt.

**Comment by oskardotglobal** [comment]
pre-commit.ci autofix

**Review by oskardotglobal — CHANGES_REQUESTED** [review]
@KernelGhost Please go ahead and merge main into your repo and then you're good to revert deec264.

You're right though, it's a good idea to keep the deprecation of virt-manager out of this PR. After those changes are done and this is re-reviewed we can merge ASAP.

**Comment by oskardotglobal** [comment]
Again, thanks for the great work @KernelGhost

**Comment by oskardotglobal** [comment]
Merge your branch with upstream please, because else the pre-commit checks won't pass

**Review by KernelGhost — COMMENTED** [review]
These auto fixes look sensible.

**Comment by oskardotglobal** [comment]
pre-commit.ci autofix

**Comment by KernelGhost** [comment]
The latest set of commits now resolve #136 by integrating compatibility with the official [FreeRDP Flatpak](https://flathub.org/apps/com.freerdp.FreeRDP) into the WinApps installer. This eliminates the need to reinstate support for FreeRDP version 2. In cases where FreeRDP version 3 is not available via the package manager on a particular distribution, users can install the Flatpak and adjust permissions accordingly to enable access to their home directory. The instructions to do this are straightforward and have been added to the project README.

**Comment by oskardotglobal** [comment]
@KernelGhost shellcheck is currently failing
By the way, you can install pre-commit via pip or your preferred package manager to run those checks locally

**Comment by KernelGhost** [comment]
Thanks for pointing that out, there was a misspelling in a variable. I've installed pre-commit and will run it locally from now on.

**Comment by oskardotglobal** [comment]
pre-commit.ci autofix

**Comment by oskardotglobal** [comment]
Yeah I currently don't know why pre-commit.ci isn't able to run the automatic fixes
Try running `pre-commit install` inside the repo and then amending the last commit

**Comment by KernelGhost** [comment]
The output remains unchanged 😔

```
RohanBarar@Latitude-5320:~/winapps$ pre-commit install
pre-commit installed at .git/hooks/pre-commit
```

```
RohanBarar@Latitude-5320:~/winapps$ pre-commit run --all-files
Set file permissions.....................................................Passed
CRLF end-lines checker...................................................Passed
CRLF end-lines remover...................................................Passed
No-tabs checker..........................................................Failed
- hook id: forbid-tabs
- exit code: 1

Tabs detected in file: bin/winapps
Tabs detected in file: install/inquirer.sh
Tabs detected in file: installer.sh

Tabs remover.............................................................Failed
- hook id: remove-tabs
- exit code: 1
- files were modified by this hook

Substituting tabs in: bin/winapps by 2 whitespaces

Tabs have been successfully removed. Now aborting the commit.
You can check the changes made. Then simply "git add --update ." and re-commit
Substituting tabs in: install/inquirer.sh by 2 whitespaces

Tabs have been successfully removed. Now aborting the commit.
You can check the changes made. Then simply "git add --update ." and re-commit
Substituting tabs in: installer.sh by 2 whitespaces

Tabs have been successfully removed. Now aborting the commit.
You can check the changes made. Then simply "git add --update ." and re-commit

check for added large files..............................................Passed
check for case conflicts.................................................Passed
check that executables have shebangs.....................................Passed
check json...........................................(no files to check)Skipped
check for merge conflicts................................................Passed
check that scripts with shebangs are executable..........................Passed
check for broken symlinks............................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
check vcs permalinks.....................................................Passed
check xml................................................................Passed
check yaml...............................................................Passed
detect destroyed symlinks................................................Passed
detect private key.......................................................Passed
fix end of files.........................................................Passed
fix utf-8 byte order marker..............................................Passed
forbid new submodules................................(no files to check)Skipped
forbid submodules....................................(no files to check)Skipped
mixed line ending........................................................Passed
pretty format json...................................(no files to check)Skipped
sort simple yaml files...............................(no files to check)Skipped
trim trailing whitespace.................................................Passed
shfmt....................................................................Failed
- hook id: shfmt
- files were modified by this hook
shellcheck...............................................................Passed
```

**Comment by oskardotglobal** [comment]
Try running `git commit --amend`

**Comment by KernelGhost** [comment]
Just a thought - It could be the case that `shfmt` is introducing tabs whilst `remove-tabs` is attempting to remove them?

**Comment by KernelGhost** [comment]
Yep. That was the issue. I will modify `.pre-commit-config.yaml` to avoid others having the same issue.

**Review by oskardotglobal — APPROVED** [review]
LGTM.

**Review by LDprg — APPROVED** [review]
Those are a lot of great refinements. Seems fine for merging to me.

**Pull request merged**
