### PR TITLE
Relicense legacy to Unlicense

### PR DESCRIPTION
**Pull request by oskardotglobal**
I have created a CLA, added it to CLA-Assistant, included the Code Covenant Code of Conduct and have written some contribution guidelines. We now only require fmstrat to sign the CLA and then we're golden.

### CODE REVIEW

**Comment by oskardotglobal** [comment]
I'll contact fmstrat

**Comment by oskardotglobal** [comment]
Aight, I've sent out the e-mail and cc'ed all of you (except you, @freechelmi, I couldn't find any email to contact you with)

**Comment by oskardotglobal** [comment]
Once thats done, we add the license

**Review by fbartels — APPROVED** [review]

**Comment by fbartels** [comment]
> I'll contact fmstrat

Thanks for reaching out to him. Good email.

**Comment by oskardotglobal** [comment]
Thank you. Now lets hope fmstrat / Ben will respond and sign the CLA

**Comment by oskardotglobal** [comment]
> Hi Oskar,
> 
> I'm happy to see the community has kept this project alive. I'm traveling this week, but will reach out when I return and can review the below.
> 
> Thanks,
> Ben

fmstrat responded! Once he signs the CLA we can merge this and then we're officially out of any legal trouble that might occur. We can also ask if he would be able to link our project on the original projects readme

**Comment by LDprg** [comment]
A small improvement would be a issue template, because following questions could be asked almost on every issue:

- which distro
- Wayland or X11
- Desktop Environment 
- legacy or rewrite
- quickemu or custom vm

**Comment by oskardotglobal** [comment]
Good idea.

**Comment by AkechiShiro** [comment]
Any update on this @oskardotglobal @LDprg, I can work on this if needed

**Comment by oskardotglobal** [comment]
There's no work to be done here.
We have to wait for Fmstrat to approve the relicense in order to be able to legally do stuff with legacy winapps.

**Comment by AkechiShiro** [comment]
When was the last time we ever heard back of from Fmstrat?

**Comment by oskardotglobal** [comment]
See #11

**Comment by AkechiShiro** [comment]
> on every issue:
> 
> * which distro
> * Wayland or X11
> * Desktop Environment
> * legacy or rewrite
> * quickemu or custom vm

Could I work on creating this issue template ? Should I create an issue to track it's progress ? @oskardotglobal @LDprg

**Comment by LDprg** [comment]
@AkechiShiro this would be great. I generally think we should also make something like a bounty board for code addition wanted. Just we can track those things better.

**Comment by LDprg** [comment]
This so we know what people want to have and for developers. Like a bounty board for contributions. This would make coordination on what can and should be developed by which person on more easy.

**Comment by AkechiShiro** [comment]
@LDprg maybe activating discussion and having people vote on feature stories that could link multiples issues such as Wayland support for instance ?

**Comment by LDprg** [comment]
> @LDprg maybe activating discussion and having people vote on feature stories that could link multiples issues such as Wayland support for instance ?

Actually a great idea.

**Comment by AkechiShiro** [comment]
For contributing guidelines such as issue template, it seems I don't have the proper rights to create one, I cannot see the settings of the repo, see : https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Maybe first, I'll work on the issue template and comment it and then let @oskardotglobal or @LDprg who has the proper permission/rights update those.

**Comment by oskardotglobal** [comment]
Those are just files; as long as you have write access you can create them

**Comment by GreatNovaDragon** [comment]
Very stupid thought: Would one need fmstrat if one were to just, completly write a new program to replace installer.sh and bin/winapps? 

Thats the stuff that fmstrat did, if i am correct, right? Having looked over the code yesterday, for #87 i got a clue what everything is intended to do, and how it could be done in, lets say, my language of preferrence c#

**Comment by oskardotglobal** [comment]
No, fmstrat isn't needed if it's a complete rewrite. That's why we're working on rewriting winapps in Rust (see the rewrite branch)
This rewrite is supposed to be modular to be able to add a gui some time in the future and also has functionality to automate the creation of the VM using quickemu

**Comment by oskardotglobal** [comment]
I'm currently still working on getting the VM right, Windows unattended installation script are just kind of a pain in the ass

**Comment by LDprg** [comment]
> I'm currently still working on getting the VM right, Windows unattended installation script are just kind of a pain in the ass

It would be great if we could automate the reg file loading on docker. This would help with legacy and rewrite a lot. We could even publish a own docker image which just modifies the xml setup file.

**Comment by oskardotglobal** [comment]
This is possible with the new image.
However, it takes quite a long time to test as you have to reinstall the OS every time

**Comment by oskardotglobal** [comment]
Alright, I've gone ahead and pushed an attempt to fix our licensing dilemma.  
Basically, I've identified the files that Fmstrat wrote and that haven't been rewritten by us. Then, I've added a license header to that file declaring it as proprietary. I've then added a script which will automatically add this license header for our selected license to all files added and changed.

**Comment by oskardotglobal** [comment]
I've also taken the liberty of swapping out the license for the Unlicense, which I feel like is a better fit than the GPL given the circumstances, but I'm open to ideas.

**Comment by LDprg** [comment]
> I've also taken the liberty of swapping out the license for the Unlicense, which I feel like is a better fit than the GPL given the circumstances, but I'm open to ideas. 

Can you please explain why Unlicense suits us better? Because for me GPL looks just fine.

**Comment by oskardotglobal** [comment]
In terms of free software, the GPLv3 is a strong and good copyleft license.

The problem with it is that there is a licensor which owns and is able to restrict access to the software. This licensor has to be a legal entity, which would either have to be one of us maintainers or a separate entity.

The Unlicense releases software into the Public Domain. In the Public Domain, the software is owned by nobody, access is possible to everybody and there are no restrictions of it's use. In that case, we do not need a legal entity to represent us. Also, we do not have the conflict of technically re-licensing someone else's work (in the case of Fmstrat); the work is clearly attributed to it's original author where required and all of our changes are released into the public domain.

**Comment by oskardotglobal** [comment]
Is everyone OK with these changes? Can I merge this?

**Comment by freechelmi** [comment]
LGTM :-)

**Comment by AkechiShiro** [comment]
Thanks @oskardotglobal 

I'm just wondering if some company can just come and relicense our code, that isn't possible ? I mean that with AGPLv3 that would be a violation but as you'd said we'd need a legal entity and we don't have that.

**Comment by GreatNovaDragon** [comment]
Pretty much not okay with putting code I partially wrote into the unlicense, therefore this PR can be closed because a license change requires consent of all devs

**Comment by GreatNovaDragon** [comment]
The Unlicense, putting it into public domain, is  incompatile with german copyright law.

I am a citizen of germany, so, that clause is not even possible to be used for this, there is no law that actually allows me to transfer copyright anywhere besides per inheritance when i die.

**Comment by GreatNovaDragon** [comment]
My understanding was that i would contribute under the GPL, and i did. That license is also irrevocable

**Comment by oskardotglobal** [comment]
@GreatNovaDragon 

I am not a lawyer. However, you have signed [this document](https://gist.github.com/oskardotglobal/35f0a72eb45fcc7087e535561383dbc5) through the CLA-Assistant. From what I understand, this document makes the signee give up their rights completely, the only exception being if the licensor violates "the principles of Free Software" by for example making the software proprietary.

We added this CLA specifically because we were planning on relicensing to a GPLv3, but both right now and when you contributed this project has no license and is technically closed-source software. 

However, I now think that we can get by with this by marking some files as proprietary. This would mean that some of the files that cannot be considered a rewrite from the original repository are attributed to their original author and marked as proprietary via a license header. For all other files, a CI step will add all new committers as copyright owners for the changed files. This would mean that all contributors retain their copyright and we could get rid of the CLA. Then, it would be no problem to keep using the GPLv3, which is what I have done in #240.  
This of course will require a new CLA to be set in place, but it would be a much simpler document simply stating that the signee agrees to have their work licensed under a GPLv3, but retaining their copyright.

For more information about the CLA you signed, see <https://fsfe.org/activities/fla/fla.html>.

**Comment by oskardotglobal** [comment]
Ok, I maybe should've read that link I sent more carefully.  
What I said is partially incorrect. You do not give up your rights in the work. From the article:

> The Contributor does not lose all of their rights, just the exclusivity in them. While the Contributor transfers their exclusive rights to the entity responsible for managing, the Trustee reciprocally grants the Contributor a non-exclusive worldwide, royalty-free, perpetual and irrevocable licence to same extent as it was originally transferred from the Contributor.

However, the article explicitely mentions that it allows the Trustee to relicense the software at will if the license is OSI or FSF-approved.

**Comment by oskardotglobal** [comment]
This does not change what I've done in #240 however. As per your request, the project will stay on the GPLv3.

**Comment by GreatNovaDragon** [comment]
Publishing my code under the Unlicense would be waiving not only my, but every contributors, moral rights and every other right, something prevented by the the CLA,  2.2 Moral Rights

**Comment by GreatNovaDragon** [comment]
Even if i were to allow it, its still impossible via 9.1

> 9.1 This Agreement and all disputes, claims, actions, suits or other proceedings arising out of this agreement or relating in any way to it shall be governed by the laws of Germany excluding its private international law provisions.

And, the german law has no mechanic to put something into the public domain, as the Unlicense tries to do. The term "public domain" is not a legal term, it's strictly US-specific. So it bears no meaning legally outside US. (So in reality US is special here, not "the rest of the world".)

**Comment by oskardotglobal** [comment]
Like I said, I am not a lawyer. Read my previous comments, we're staying on the GPL. (Or technically relicensing to the GPL.)

**Comment by AkechiShiro** [comment]
Could we maybe see if it's worth to change from GPLv3 to perhaps this one, what do you think @oskardotglobal ? 

https://commission.europa.eu/content/european-union-public-licence_en

> The licence should have equal legal value in many languages
> The terminology regarding intellectual property rights had to be conformant with the European law requirements 
> To be valid in all Member States, limitations of liability or warranty had to be precise, and not formulated "to the extent allowed by the law" as in most licences designed with the legal environment of the United States in mind

Here is the full license text in English : https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_en.pdf

Feel free to state any objection @GreatNovaDragon but I think this one is compliant with any laws that Germany has.

**Comment by oskardotglobal** [comment]
@AkechiShiro This seems like a good idea. Let's further talk about this in #240.

**Pull request merged**
