### PR TITLE
Precommit for legacy

### PR DESCRIPTION
**Pull request by LDprg**
This is still wip and will need extensive testing when ready.

Since a there is a lot of formatting and manual fixing.

### CODE REVIEW

**Comment by oskardotglobal** [comment]
pre-commit.ci autofix

**Comment by LDprg** [comment]
This is basically ready for early review and testing. Note that I DIDN'T TEST THIS, so it shouldn't be right up merged.

**Comment by LDprg** [comment]
Btw for testing I can really recommend using distrobox. (I know docker in docker is kinda strange but it works). It allows us to create a clean environment and test different distros without installing a vm for like 20 minutes.

**Comment by oskardotglobal** [comment]
Ok I'm having quite a bit of trouble getting winapps to work; it just refuses on my Nix machine
The problem is that both the domain and the password have to be empty in my case and due to shell escaping the command winapps runs becomes
```bash
xfreerdp /p: /d: /u:Docker /scale:100 +auto-reconnect +home-drive -wallpaper +dynamic-resolution +span /app:program:explorer.exe /v:127.0.0.1
```
instead of
```bash
xfreerdp /p:"" /d:"" /u:Docker /scale:100 +auto-reconnect +home-drive -wallpaper +dynamic-resolution +span /app:program:explorer.exe /v:127.0.0.1
```
which works completely fine

**Comment by oskardotglobal** [comment]
Any suggestions?

**Review by oskardotglobal — APPROVED** [review]
Looks good. Works on my machine.

**Comment by oskardotglobal** [comment]
I've also found a fix for my above problem & included the automatic installation of the reg file in this PR too

**Comment by LDprg** [comment]
@oskardotglobal can you update the docs accordingly?

**Comment by oskardotglobal** [comment]
Yeah, sure

**Comment by oskardotglobal** [comment]
.. Why does pre-commit remove the double spaces after lines
They represent line breaks in Markdown

**Comment by oskardotglobal** [comment]
pre-commit.ci autofix

**Comment by LDprg** [comment]
> .. Why does pre-commit remove the double spaces after lines
> They represent line breaks in Markdown

Propably some tab/line ending fixing precommit hook.

**Comment by CiRiX-** [comment]
What about this issue here? https://github.com/winapps-org/winapps/issues/91

The newer freerdp releases wont start apps.

**Comment by oskardotglobal** [comment]
@CiRiX- 
That seems like an issue with the user's specific version or with the changed syntax of the `/app` argument
I don't wanna be *that* guy, but it seems like a skill issue; I'm running freerdp 3.5.1 on my Nix machine and it works just fine

**Comment by LDprg** [comment]
@oskardotglobal we might add a switch for the /app syntax depending on the freerdp version?

This would work around some package manager not providing any freerdp 3 packages.

Or we ship a working freerdp v3 command with winapps.

**Comment by oskardotglobal** [comment]
I think shipping a binary would be a good approach, but that would require the binary to not be linked against OS libraries since otherwise you would have to install a bunch of dependencies

**Comment by CiRiX-** [comment]
@oskardotglobal 
Don't worry, you are probably right :wink: 
I am not super experienced with Linux, and i'm not a programmer.

I think it should be more user friendly, so shipping a working version like @LDprg said would be a good idea i guess.

**Comment by AkechiShiro** [comment]
Maybe we'd need to work a wrapper for Xfreerdp (in Bash maybe, that simplifies usage) ?

**Pull request merged**
