### PR TITLE
Clean up old network profiles

### PR DESCRIPTION
**Pull request by itiligent**
As requested by @oskardotglobal. This PR will help keep Windows networking tidy. The install.bat changes will:
1. Create a new powershell script and save this to c:\windows. The Powershell script will clear unused network profile names that were automatically created at previous system reboots.
2. Install.bat also creates a new scheduled task that will run the cleanup powershell script at boot 
3. A registry change is further added to RDPapps.reg to disable the "Do you want your PC to be discoverable" nag screen after each reboot
4. I've also added simple comments to each of the reg file entries for clarity.

### CODE REVIEW

**Review by oskardotglobal — CHANGES_REQUESTED** [review]
This looks good to me. However, could you please merge upstream/main into your local branch so that the license checks can add you as a copyright owner to the `install.bat`?

**Comment by itiligent** [comment]
sorry, my bad. Done now.

**Comment by oskardotglobal** [comment]
The CI doesn't seem to be picking up on your changes, can you add yourself to the copyright header of the file manually?

**Comment by itiligent** [comment]
I'm sorry I don't understand what you mean

**Comment by itiligent** [comment]
Having issues with the copyright thingy. I will delete this PR, re-sync my fork and recreate the PR to see if that helps.

**Pull request closed without merging**
