### PR TITLE
Cli and config parsing

### PR DESCRIPTION
**Pull request by LDprg**
In order to start the rewrite, I did just some cli and config file parsing. Nothing special.

### CODE REVIEW

**Comment by oskardotglobal** [comment]
Looks good so far, but why are you converting the string literal to a string when creating default values for the constructor using `#[new(value = "\"RDPWindows\".to_string()")]`. Couldn't you use `#[new(value = "\"RDPWindows\"")]`

**Comment by LDprg** [comment]
It is a rust thing, it comes from the difference between &str and String. The default values are &str and the struct fiels are Strings, so that stuff works out I need to convert &str to String. The fact that the conversion happen in a string and not as code is the way the default makro works (looked this up on the github page)

**Review by oskardotglobal — APPROVED** [review]
Aight, was just asking since I'm not that familiar with rust. If thats not problematic, I'll approve this

**Comment by LDprg** [comment]
Just added some more error checking. I merge it as soon as the rust checks are ready.

**Pull request merged**
