### PR TITLE
Added WinApps Launcher as a submodule

### PR DESCRIPTION
**Pull request by KernelGhost**

### CODE REVIEW

**Review by LDprg — APPROVED** [review]
I am fine with adding the launcher as submodule.

**Comment by oskardotglobal** [comment]
pre-commit.ci autofix

**Review by oskardotglobal — CHANGES_REQUESTED** [review]
We might want to add something to automatically update this submodule though. We could implement something like https://tommoa.me/blog/github-auto-update-submodules/

**Review by oskardotglobal — APPROVED** [review]
Something like this should work.

**Comment by oskardotglobal** [comment]
pre-commit.ci autofix

**Comment by KernelGhost** [comment]
Is everyone okay with proceeding to merge this?

**Pull request merged**
