### PR TITLE
Improve sound and microphone sharing.

### PR DESCRIPTION
**Pull request by RheaBarar**
Replaced `/audio-mode:1` with `/sound /microphone`. May help address #169.

### CODE REVIEW

**Comment by KernelGhost** [comment]
This seems like a better way to do things. I have confirmed this change works well with my `libvirt`-based Windows virtual machine. LGTM.

**Review by KernelGhost — APPROVED** [review]
This seems like a better way to do things. I have confirmed this change works well with my libvirt-based Windows virtual machine. LGTM.

**Comment by itiligent** [comment]
This does not solve #169
Would't the most intuitive way to solve this be to remove all reference to /sound and /microphone merged in b6f6a93 and instead simply pass these audio values to winapps following using the very standard convention a config file? i.e.   ~/.config/winapps/winapps.conf.

The way this is currently in implemented in b6f6a93 produces the same issue in #169 whereby sound config settings buried deep in git source *override* whatever audio values are added to the config file.  Also, any manual audio settings changes made to source will get overwritten with subsequent git clone updates or reinstalls, whereas a good old config file will keep the desired audio values regardless....which to me makes far more sense (and would have saved me a few wasted evenings a few weeks back!)

Or.. am I missing something as to why it must be done the current way?

**Comment by KernelGhost** [comment]
@itiligent, you make a good point. There's no need for this to be handled in the shell script instead of the configuration file. Could you please submit a PR to move the audio settings `/sound` and `/microphone` into the default configuration file template?

**Comment by oskardotglobal** [comment]
While we're at it, `/cert:tofu` should also be moved there

**Comment by itiligent** [comment]
Ok, to clarifiy before I make a PR, you would like to remove instances of /cert:tofu, /sound & /microphone in the /bin/winapps file, and instead add these as (enabled) default options in the RDP_FLAGS line?  e.g. `RDP_FLAGS="/cert:tofu /sound /microphone"`

**Comment by KernelGhost** [comment]
That looks perfect, yes. Could you also please test the changes before submitting the PR? Thanks so much!

**Pull request merged**
